site_name: ondroid
site_url: https://ondroid.ai

nav:
  - Getting Started:
    - gettingStarted/index.md
    - Mission: gettingStarted/mission.md
  - Glossary: glossary.md
  - DevOps:
    - devops/index.md
    - Mechanical DevOps:
      - CAD: devops/mechanical/cad.md
      - Allowed Packages: devops/mechanical/cadPackages.md
    - Software DevOps:
      - devops/software/index.md
  - Analysis: 
    - analysis/index.md
    - System:
      - system/index.md
    - Arms:
      - Arm, L:
        - analysis/arms/arm, L/index.md
        - Arm, L Calculations:
          - Arm Calculations, L, 1: analysis/arms/arm, L/notebook.ipynb
  - Design and Engineering:
    - design/index.md
    - Design Constraints: design/constraints.md
    - Concept Design: design/conceptDesign.md

theme:
  logo: assets/logo1.png
  favicon: assets/logo1.png

  name: material
  features:
    - navigation.expand
      #- navigation.prune
    - navigation.indexes
      #- navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en

  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: grey
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch Mode
      primary: grey
      accent: purple 

plugins:
  - mkdocs-jupyter
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emoshou/ondroid/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

  - pymdownx.arithmatex:
      generic: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
