site_name: ondroid
site_url: https://ondroid.ai

nav:
  - Getting Started:
    - gettingStarted/index.md
    - Mission: mission.md
  - Calculations: 
    - calculations/index.md
    - Arms:
      - Arm, L: calculations/calculations_arm.md
      - Arm Calculations, L, 1: notebook.ipynb
  - Design:
    - CAD: cad.md

theme:
  name: material
  features:
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en

  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: grey
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch Mode
      primary: grey
      accent: purple 

plugins:
  - mkdocs-jupyter
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emoshou/ondroid/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

  - pymdownx.arithmatex:
      generic: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
